### PR TITLE
chore: setup absolute imports

### PR DESCRIPTION
**Pull request by tj3407**
This PR sets up absolute imports as described in https://nextjs.org/docs/advanced-features/module-path-aliases

For issue #42

### CODE REVIEW

**Comment by tj3407** [comment]
@SamSamskies .. Thanks for letting me contribute! Let me know if you were looking for a specific convention when doing absolute imports and I can change. Thanks!

**Comment by SamSamskies** [comment]
@tj3407 thanks for the PR! 

I think we can simplify things by removing the paths. Just setting the baseURL should be good enough.

**Comment by tj3407** [comment]
> @tj3407 thanks for the PR!
> 
> I think we can simplify things by removing the paths. Just setting the baseURL should be good enough.

Got it! This has been changed. Let me know if you see any issues. Thanks!

**Comment by SamSamskies** [comment]
lgtm. i'll test out the changes later. thanks.

**Pull request merged**
